/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import javax.swing.JOptionPane;

/**
 *
 * @author Pramodhi
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        productupdateb1 = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        homeb3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        userb2 = new javax.swing.JButton();
        productupdateb2 = new javax.swing.JButton();
        userb3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bodoni MT Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin Home Page");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 27, 260, 36));

        productupdateb1.setBackground(new java.awt.Color(51, 153, 255));
        productupdateb1.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        productupdateb1.setForeground(new java.awt.Color(0, 0, 102));
        productupdateb1.setText("Product List ");
        productupdateb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productupdateb1ActionPerformed(evt);
            }
        });
        jPanel1.add(productupdateb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 239, -1));

        logoutbtn.setBackground(new java.awt.Color(51, 153, 255));
        logoutbtn.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        logoutbtn.setForeground(new java.awt.Color(0, 0, 102));
        logoutbtn.setText("Log Out");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 239, -1));

        jLabel7.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Back to home page");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        homeb3.setBackground(new java.awt.Color(51, 153, 255));
        homeb3.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        homeb3.setForeground(new java.awt.Color(0, 0, 102));
        homeb3.setText("Home");
        homeb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeb3ActionPerformed(evt);
            }
        });
        jPanel1.add(homeb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pramodhi\\Documents\\NetBeansProjects\\KellerSports\\pictures\\Keller_Sports__2_-removebg-preview.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 440, 380));

        userb2.setBackground(new java.awt.Color(51, 153, 255));
        userb2.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        userb2.setForeground(new java.awt.Color(0, 0, 102));
        userb2.setText("Customer Update & Details");
        userb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userb2ActionPerformed(evt);
            }
        });
        jPanel1.add(userb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 239, -1));

        productupdateb2.setBackground(new java.awt.Color(51, 153, 255));
        productupdateb2.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        productupdateb2.setForeground(new java.awt.Color(0, 0, 102));
        productupdateb2.setText("Product Update ");
        productupdateb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productupdateb2ActionPerformed(evt);
            }
        });
        jPanel1.add(productupdateb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 239, -1));

        userb3.setBackground(new java.awt.Color(51, 153, 255));
        userb3.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        userb3.setForeground(new java.awt.Color(0, 0, 102));
        userb3.setText("Order Update & Details");
        userb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userb3ActionPerformed(evt);
            }
        });
        jPanel1.add(userb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 239, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(706, 424));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void productupdateb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productupdateb1ActionPerformed
        Products products = new Products();
        products.setVisible(true);
        this.dispose();     }//GEN-LAST:event_productupdateb1ActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Do you want to log out?");         

        if(response==0){
            LogOut lg=new LogOut();
            lg.setVisible(true);
            this.dispose();
        }
        else {

            this.setVisible(true);

        }
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void homeb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeb3ActionPerformed
        Home homePage = new Home();
        homePage.setVisible(true);
        this.dispose();     }//GEN-LAST:event_homeb3ActionPerformed

    private void userb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userb2ActionPerformed
        CustomerDetails customerDetails = new CustomerDetails();
        customerDetails.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userb2ActionPerformed

    private void productupdateb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productupdateb2ActionPerformed
        ProductUpdate productupdate = new ProductUpdate();
        productupdate.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_productupdateb2ActionPerformed

    private void userb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userb3ActionPerformed

        Orders ordersPage = new Orders();
        ordersPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userb3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeb3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton productupdateb1;
    private javax.swing.JButton productupdateb2;
    private javax.swing.JButton userb2;
    private javax.swing.JButton userb3;
    // End of variables declaration//GEN-END:variables
}
