/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author Pramodhi
 */
public class Products extends javax.swing.JFrame {

    /**
     * Creates new form Products
     */
    public Products() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        category2 = new javax.swing.JButton();
        category3 = new javax.swing.JButton();
        category1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        homeb3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        category4 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bodoni MT Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Categories");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 260, 36));

        category2.setBackground(new java.awt.Color(51, 153, 255));
        category2.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        category2.setForeground(new java.awt.Color(0, 0, 102));
        category2.setText("Equipments");
        category2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category2ActionPerformed(evt);
            }
        });
        jPanel1.add(category2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 190, -1));

        category3.setBackground(new java.awt.Color(51, 153, 255));
        category3.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        category3.setForeground(new java.awt.Color(0, 0, 102));
        category3.setText("Shoes");
        category3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category3ActionPerformed(evt);
            }
        });
        jPanel1.add(category3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 190, -1));

        category1.setBackground(new java.awt.Color(51, 153, 255));
        category1.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        category1.setForeground(new java.awt.Color(0, 0, 102));
        category1.setText("Clothes");
        category1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category1ActionPerformed(evt);
            }
        });
        jPanel1.add(category1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 190, -1));

        jLabel7.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Back to user home page");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, -1, -1));

        homeb3.setBackground(new java.awt.Color(51, 153, 255));
        homeb3.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        homeb3.setForeground(new java.awt.Color(0, 0, 102));
        homeb3.setText("Admin Home");
        homeb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeb3ActionPerformed(evt);
            }
        });
        jPanel1.add(homeb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pramodhi\\Documents\\NetBeansProjects\\KellerSports\\pictures\\shoes\\114.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 190, 170));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pramodhi\\Documents\\NetBeansProjects\\KellerSports\\pictures\\Untitled design (10).png")); // NOI18N
        jLabel5.setText("jLabel3");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 190, 170));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pramodhi\\Documents\\NetBeansProjects\\KellerSports\\pictures\\Untitled design (11).png")); // NOI18N
        jLabel6.setText("jLabel3");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 190, 170));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pramodhi\\Documents\\NetBeansProjects\\KellerSports\\pictures\\Untitled design (12).png")); // NOI18N
        jLabel4.setText("jLabel3");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 190, 170));

        category4.setBackground(new java.awt.Color(51, 153, 255));
        category4.setFont(new java.awt.Font("Bodoni MT Black", 1, 12)); // NOI18N
        category4.setForeground(new java.awt.Color(0, 0, 102));
        category4.setText("Others");
        category4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category4ActionPerformed(evt);
            }
        });
        jPanel1.add(category4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1049, 477));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeb3ActionPerformed
        AdminHome adminHomePage = new AdminHome();
        adminHomePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeb3ActionPerformed

    private void category1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category1ActionPerformed
        Clothes clothesPage = new Clothes();
        clothesPage.setVisible(true);
        this.dispose();    }//GEN-LAST:event_category1ActionPerformed

    private void category3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category3ActionPerformed
        Shoes shoesPage = new Shoes();
        shoesPage.setVisible(true);
        this.dispose();    }//GEN-LAST:event_category3ActionPerformed

    private void category2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category2ActionPerformed
        Equipments equipmentsPage = new Equipments();
        equipmentsPage.setVisible(true);
        this.dispose();    }//GEN-LAST:event_category2ActionPerformed

    private void category4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category4ActionPerformed
        Others othersPage= new Others();
        othersPage.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_category4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton category1;
    private javax.swing.JButton category2;
    private javax.swing.JButton category3;
    private javax.swing.JButton category4;
    private javax.swing.JButton homeb3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
